package de.due.ldsa.ld.model;

public enum RelationshipStatus {
	SINGLE, TAKEN, ENGAGED, MARRIED, CIVILUNION, DOMESTIC_PARTNER, OPEN_RELATIONSHIP, 
	COMPLICATED, SEPARATED, DIVORCED, WIDOWED, UNKNOWN

}
